vim.api.nvim_set_hl(0, "Normal", {fg="#d5c6e0", bg="#16161D"})
vim.api.nvim_set_hl(0, "NormalFloat", {bg="NONE"})
vim.api.nvim_set_hl(0, "Identifier", {fg="#d5c6e0"})
vim.api.nvim_set_hl(0, "TermCursor", {reverse=true})
vim.api.nvim_set_hl(0, "Cursor", {fg="bg", bg="fg"})
vim.api.nvim_set_hl(0, "lCursor", {fg="bg", bg="fg"})
vim.api.nvim_set_hl(0, "CursorLine", {bg="#373e40"})
vim.api.nvim_set_hl(0, "CursorColumn", {bg="#030707"})
vim.api.nvim_set_hl(0, "CursorLineLir", {bg="#984695"})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg="#75797a"})
vim.api.nvim_set_hl(0, "LineNr", {fg="#686858"})
vim.api.nvim_set_hl(0, "Directory", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg="#403d39"})
vim.api.nvim_set_hl(0, "IncSearch", {bg="#984695"})
vim.api.nvim_set_hl(0, "Search", {fg="#16161D", bg="#9ef01a"})
vim.api.nvim_set_hl(0, "MatchParen", {bg="NONE", fg="#9ef01a"})
vim.api.nvim_set_hl(0, "MoreMsg", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "ModeMsg", {bold=true})
vim.api.nvim_set_hl(0, "Question", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "StatusLine", {fg="#75797a"})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg="#75797a"})
vim.api.nvim_set_hl(0, "SignColumn", {bg="NONE"})
vim.api.nvim_set_hl(0, "VertSplit", {fg="#984695", bg="bg"})
vim.api.nvim_set_hl(0, "Title", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "Visual", {bg="#703871"})
vim.api.nvim_set_hl(0, "WarningMsg", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "WildMenu", {fg="Black", bg="Yellow"})
vim.api.nvim_set_hl(0, "Folded", {bg="#030707"})
vim.api.nvim_set_hl(0, "DiffAdd", {bg="#182822"})
vim.api.nvim_set_hl(0, "DiffChange", {bg="#182822"})
vim.api.nvim_set_hl(0, "DiffDelete", {bg="bg"})
vim.api.nvim_set_hl(0, "DiffText", {bg="#304936"})
vim.api.nvim_set_hl(0, "Conceal", {fg="#7b3f58"})
vim.api.nvim_set_hl(0, "SpellBad", {undercurl=true, sp="#c51af9"})
vim.api.nvim_set_hl(0, "SpellCap", {undercurl=true, sp="#fc735d"})
vim.api.nvim_set_hl(0, "SpellRare", {undercurl=true, sp="#fb3475"})
vim.api.nvim_set_hl(0, "SpellLocal", {undercurl=true, sp="#d694fa"})
vim.api.nvim_set_hl(0, "Pmenu", {bg="#030707"})
vim.api.nvim_set_hl(0, "PmenuSel", {fg="#9ef01a", bg="#403d39"})
vim.api.nvim_set_hl(0, "PmenuSbar", {bg="#030707"})
vim.api.nvim_set_hl(0, "TabLine", {fg="#75797a"})
vim.api.nvim_set_hl(0, "TabLineSel", {fg="#75797a", bg="bg"})
vim.api.nvim_set_hl(0, "TabLineFill", {fg="#75797a"})
vim.api.nvim_set_hl(0, "ColorColumn", {bg="#030707"})
vim.api.nvim_set_hl(0, "FloatBorder", {fg="#75797a"})
vim.api.nvim_set_hl(0, "WinBar", {bold=true})
vim.api.nvim_set_hl(0, "FloatShadow", {bg="Black", blend=80})
vim.api.nvim_set_hl(0, "FloatShadowThrough", {bg="Black", blend=100})
vim.api.nvim_set_hl(0, "RedrawDebugNormal", {reverse=true})
vim.api.nvim_set_hl(0, "RedrawDebugClear", {bg="Yellow"})
vim.api.nvim_set_hl(0, "RedrawDebugComposed", {bg="Green"})
vim.api.nvim_set_hl(0, "RedrawDebugRecompose", {bg="Red"})
vim.api.nvim_set_hl(0, "Todo", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "String", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "Constant", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "Function", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "Conditional", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "Statement", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "Repeat", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "Operator", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "Keyword", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "Include", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "PreProc", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "Type", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "Tag", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "Special", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "Delimiter", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg="#75797a"})
vim.api.nvim_set_hl(0, "DiagnosticOk", {fg="LightGreen"})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {undercurl=true, sp="#fc735d"})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {undercurl=true, sp="#b194fa"})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {undercurl=true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineOk", {underline=true, sp="LightGreen"})
vim.api.nvim_set_hl(0, "Comment", {italic=true, fg="#686858"})
vim.api.nvim_set_hl(0, "Underlined", {underline=true, fg="#80a0ff"})
vim.api.nvim_set_hl(0, "Ignore", {fg="bg"})
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", {strikethrough=true, fg="#75797a"})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindText", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg="#eaf3f5"})
vim.api.nvim_set_hl(0, "CmpItemAbbrDefault", {fg="#eaf3f5"})
vim.api.nvim_set_hl(0, "CmpItemKindDefault", {fg="#75797a"})
vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "CmpItemKindField", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "LspReferenceText", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "LspReferenceRead", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "GitSignsChange", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "GitSignsDelete", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "GitSignsAdd", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "GitSignsDeletePreview", {fg="#eaf3f5", bg="#321a26"})
vim.api.nvim_set_hl(0, "GitSignsAddInline", {bg="#304936"})
vim.api.nvim_set_hl(0, "TabbyHL_f2e9de_1b2021_NONE", {fg="#f2e9de", bg="#1b2021"})
vim.api.nvim_set_hl(0, "TabbyHL_5f506b_1b2021_NONE", {fg="#5f506b", bg="#1b2021"})
vim.api.nvim_set_hl(0, "TabbyHL_ffe5d9_5f506b_NONE", {fg="#ffe5d9", bg="#5f506b"})
vim.api.nvim_set_hl(0, "TabbyHL_1b2021_1b2021_NONE", {fg="#1b2021", bg="#1b2021"})
vim.api.nvim_set_hl(0, "TabbyHL_1b2021_5f506b_NONE", {fg="#1b2021", bg="#5f506b"})
vim.api.nvim_set_hl(0, "TabbyHL_f2e9de_5f506b_NONE", {fg="#f2e9de", bg="#5f506b"})
vim.api.nvim_set_hl(0, "mkdCodeDelimiter", {fg="#75797a"})
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextWarning", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", {fg="#75797a"})
vim.api.nvim_set_hl(0, "CmpDocumentation", {bg="#030707"})
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {fg="#75797a"})
vim.api.nvim_set_hl(0, "markdownCode", {fg="#75797a"})
vim.api.nvim_set_hl(0, "gitcommitSummary", {fg="#b194fa"})
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", {fg="#75797a"})
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", {fg="#75797a"})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg="#517751"})
vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg="#a14f42"})
vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg="#a02851"})
vim.api.nvim_set_hl(0, "NvimTreeGitDirty", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "NvimTreeRootFolder", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "TelescopeSelection", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "TelescopeBorder", {fg="#030707", bg="#030707"})
vim.api.nvim_set_hl(0, "TelescopeMatching", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "mkdCde", {fg="#75797a"})
vim.api.nvim_set_hl(0, "mkdListItem", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "mkdHeading", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "vimOption", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "gitcommitDiscardedType", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "gitcommitSelectdType", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "gitcommitUnmergedFile", {fg="#fcc25d"})
vim.api.nvim_set_hl(0, "gitcommitSelectedFile", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "gitcommitUnmerged", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "gitcommitOverflow", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "Noise", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "TelescopePromptTitle", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "NotifyBackground", {bg="bg"})
vim.api.nvim_set_hl(0, "LuasnipInsert", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "LuasnipChoice", {fg="#c51af9"})
vim.api.nvim_set_hl(0, "LirEmptyDirText", {bg="#984695"})
vim.api.nvim_set_hl(0, "LirDir", {fg="#fc735d"})
vim.api.nvim_set_hl(0, "NotifyLogTitle", {fg="#7cb375"})
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", {fg="#b194fa", bg="#984695"})
vim.api.nvim_set_hl(0, "gitcommitHeader", {fg="#d694fa"})
vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg="#1f1c2a", bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "gitcommitDiscardedFile", {fg="#fb3475"})
vim.api.nvim_set_hl(0, "TelescopePromptNormal", {bg="#1f1c2a"})
vim.api.nvim_set_hl(0, "TelescopeNormal", {bg="#030707"})
